[build]
  publish = "out"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20.17.0"
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production" 