[build]
  publish = "out"
  command = "npm install --legacy-peer-deps && npm list typescript && npm run build"

[build.environment]
  NODE_VERSION = "20.17.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production" 